### ISSUE TITLE
Strange value "AMS reader Accumulated reactive export"

### ISSUE THREAD

**Issue by HanspeterH** [ehorvat1/NES-MEP-Reader#8]
Hi Bert
I added my NES smartreader to homeasssistant using MQTT. Subscribing to all topics (#) I get 35 different values displayed in the homeassistant dash board. This works ok, but the field "AMS reader Accumulated reactive export" shows strange values: First of all I do not export power and second the value floats between positive and negative, small and very lage numbers. To me it looks, as if the field was not properly initialzed in the SW or that the NES meter delivers wrong or uninitialzed values.
Could you please have a look at this?
Thanks, Hanspeter

**Comment by HanspeterH** [comment]
Sceen capture added to above issue...
![exportproblem](https://github.com/ehorvat1/NES-MEP-Reader/assets/2361929/617f6d88-2739-496a-94c5-bf8e898dcee9)

Hanspeter

**Comment by ehorvat1** [comment]
Servus Hanspeter,
some time ago I have seen this also on my installation. It looked a strange as you described - very fast changes. So I did check the table/address where it was read from....but all seems ok in software. So no mixup or so. 
This value (ReactiveExportCounter) is derived from Table BT28 (1C) from address nr. 3 which is in line with the document "MEP Client Developer’s Guide " where BT28 is described on pages 215 ff. 
Software which copies this can be seen in file "NES-MEP.cpp at line 296 where "ExportReactiveVArL1L2L3" is filled.

Since all other values in this table are working correctly I expect that this value is not what it pretends to be....or it can not be measured exactly if there is no export. I will check this on an other installation where a exporting PV is connected.
Reg, Bert

**Comment by ehorvat1** [comment]
The above mentioned document  "MEP Client Developer’s Guide" is called "078-0372-01BD_MEP_Client_DG-OSGP%20Alliance_update3A.pdf" and can be found here: https://github.com/OSGP-Alliance-MEP-and-Optical/Documentation/tree/main 
Reg, Bert

**Comment by HanspeterH** [comment]
Hallo Bert
Thank you for your detailed answer to this problem. I therefore will just ignore this field.
Regards, Hanspeter

**Comment by git3654** [comment]
Hallo,
Das Problem ist das nicht genug Bytes im BasicTable 23 ausgelesen werden!
Es werden nur 13 Bytes augelesen, darum ändert sich der 4.8.0 so stark.
Gen 4
soll
![NES](https://github.com/ehorvat1/NES-MEP-Reader/assets/137344330/7d2c81cb-722e-4918-aae6-adc18ca3db01)
Ist
![grafik](https://github.com/ehorvat1/NES-MEP-Reader/assets/137344330/d887d338-a2f7-43a5-b9e6-172d096d36d8)
![grafik](https://github.com/ehorvat1/NES-MEP-Reader/assets/137344330/ce1eab8f-889a-4150-b04c-81d3037357cd)
Debug
![grafik](https://github.com/ehorvat1/NES-MEP-Reader/assets/137344330/6ff51934-c5fe-44ba-85a4-af77f2e946ba)
Gen 3 hier wird der gesamte BasicTable ausgelesen
![grafik](https://github.com/ehorvat1/NES-MEP-Reader/assets/137344330/0382ded1-5cd1-4dda-bdb5-a14d8ab41452)

Lg Hubert STW Amstetten

**Comment by ehorvat1** [comment]
Danke Hubert,
habe das jetzt behoben - Resultat bei mit schaut auf den ersten Blick auch sehr plausibel aus. Neues firmware.bin File ist hochgeladen.
LG, Bert

**Comment by git3654** [comment]
Danke, sieht bei mir auch gut aus.
![grafik](https://github.com/ehorvat1/NES-MEP-Reader/assets/137344330/a80e4a27-32b9-4b20-9652-c9f00fcf6c3f)
Lg Hubert

**Comment by ehorvat1** [comment]
Issue is fixed now.
